### ISSUE TITLE
ContentElement Description not shown, after update to 1.8.0

### ISSUE THREAD

**Issue by fduarte42** [lochmueller/autoloader#10]
After updating to 1.8.0 my ContentElements show no Label and/or description, when I try to add a ContentElement to a Page. Only the Icon is shown. When I downgrade to 1.7.0 everthing is working again. I tried the example autoloader_contentobject extension, and it also happens there.

**Comment by lochmueller** [comment]
Hey @fduarte42 
Do you try the current 1.9.0 version?
Regards,
Tim

**Comment by lochmueller** [comment]
I close this issue. Please try the current master or the version 1.9.0. The problem was fixed in that release...

**Comment by fduarte42** [comment]
I tested it with 1.9.1, and it does work now.
