### ISSUE TITLE
Flush autoloader cache label of version 3.2.0 under TYPO3 7.6 wrong

### ISSUE THREAD

**Issue by mediaessenz** [lochmueller/autoloader#101]
Instead of "EXT: autoloader caches" it appears "LLL:EXT:autoloader/Resources/Private/Language/locallang.xlf:cache.title"

**Comment by mediaessenz** [comment]
I have created a bugfix under https://github.com/mediaessenz/autoloader/tree/feature/101-add-correct-cache-label, but I don't find a way to create a pull request against version 3.2.0

**Comment by lochmueller** [comment]
Hey @mediaessenz 
Do you use TYPO3 7.6.x? There will be no update for the old TYPO3 Versions anymore.
Sorry. In TYPO3 8.x everthing works well...
Regards,
Tim

**Comment by mediaessenz** [comment]
I know, that this bug doesn't exists under TYPO 8.7 ;-)
But hey, there are assuredly some pages out there which still using TYPO3 7.6 ;-).

On the other hand I can understand your point as an author of a free – btw. very cool – extension, who has no big interest to maintain older branches.

But anyway, I made a fix for it, and this can be found under the link above. Maybe someone with the same problem will find this useful.

**Comment by lochmueller** [comment]
Yes. Thats right. Thank you.
I wil close this issue....
