### ISSUE TITLE
It's not possible to add database fields like sectionIndex, CType to a Domain Model

### ISSUE THREAD

**Issue by jagodzinski** [lochmueller/autoloader#105]
It's not possible to add default database fields which are not written with an underscore to a Domain Model.

By adding $sectionIndex to a Domain Model the field section_index is expected in the database but the default TYPO3 field is sectionIndex.

Other examples which should be possible to include are CType, colPos and linkToTop.

Kind regards
Jessica

**Comment by lochmueller** [comment]
Thanks... i will check this in the next days/weeks (perhaps on the TYPO3 Snowboard Tour)

**Comment by lochmueller** [comment]
Via Slack: In neueren TYPO3 Versionen befindet sich das Feld sectionIndex allerdings in der Palette appearanceLinks. Das witzige ist, dass Felder wie hidden, sectionIndex, etc. angezeigt werden, sobald man die Extension Form oder css_styled_content installiert. Dies liegt daran, dass die Palette visibility in der Datei EXT:form/Configuration/TCA/Overrides/tt_content.php wie folgt überschrieben wird:
```if (!isset($GLOBALS['TCA']['tt_content']['palettes']['visibility'])) {
   $GLOBALS['TCA']['tt_content']['palettes']['visibility'] = [
       'showitem' => '
           hidden;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:hidden_formlabel,
           sectionIndex;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:sectionIndex_formlabel,
           linkToTop;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:linkToTop_formlabel
       ',
   ];
}

**Comment by lochmueller** [comment]
Hey @jagodzinski 
A new bugfix is in the current dev-master release.
The palettes change is not so important, because if you add e.g. "sectionIndex" to your CE you will get  field directly...
Regards,
Tim
