### ISSUE TITLE
[DOCUMENTATION] localization strings overview

### ISSUE THREAD

**Issue by jousch** [lochmueller/autoloader#11]
It would be nice for new users of the ext to get an overview which prefixes (tt_content, content.element, ...) are for which area in the backend.

When you drop me a short info to every possible, I could write the documentation part with some nice backend screenshots.

**Comment by lochmueller** [comment]
This parts?

https://github.com/lochmueller/autoloader/search?utf8=%E2%9C%93&q=assureLabel

tt_content.EXTKEY.header
tt_content.UNDERSCORE_MODEL_NAME.description (ContentObjects)
backendLayout.BASENAME (BackendLayouts)
TABLENAME
TABLENAME.FIELDNAME

**Comment by jousch** [comment]
what about `wizard. ...`

**Comment by lochmueller** [comment]
I changes the list at the top...

**Comment by lochmueller** [comment]
Hey @jousch any progress on this topic?
