### ISSUE TITLE
eID for JsonServer does not initialize error handling

### ISSUE THREAD

**Issue by dev-stefan** [lochmueller/autoloader#113]
In the method JsonServer::initEnvironment() which is used in eID\JsonSever.php the initialization of the error handling is missing.

Typo3 error handling can be found in \TYPO3\CMS\Core\Core\Bootstrap::initializeErrorHandling().

Could this error handling be implemented the same way for the JsonServer?

**Comment by lochmueller** [comment]
Hmm... the method is protected. I don't know if it is a good idea to call: \TYPO3\CMS\Core\Core\Bootstrap::loadConfigurationAndInitialize ?!?! Do you try it?

**Comment by lochmueller** [comment]
Hey @dev-stefan 
I close this issue. I found no smart way to init the errorHandling without boot the complete Core-Bootstrap. If you have any news/options to do this, feel free to reopen the issue or create a new one.
Regards,
Tim
