### ISSUE TITLE
Configurable layout/template/partialPaths

### ISSUE THREAD

**Issue by pniederlag** [lochmueller/autoloader#114]
The ContentController currently adds "hardcoded" something like:

     XXXRootPaths[5] = 'EXT:' . $this->settings['extensionKey'] . '/Resources/Private/XX

First of all I am puzzled on the [5] is there a rationale on this?

My main concern is that I'd like to be able to adjust the paths here. I know I can add addiotional paths but still I'd like to keep my '/Resources/Private/XX' folders out of the config as these contain PAGE related layouts/templates and Partials. Each of these folders has a subdirectory Content which then should be used on the level of the Content-Elements. 

This is the approach of the theming team which I would like to follow.

Do you maybe have an idea/suggestion on how to get more influence on the Paths[] being added here?

Thx, always fun to use,
Peter

**Comment by lochmueller** [comment]
Hey @pniederlag ,
could you exmplain the usecase more detail?
With "plugin.tx_autoloader.view.templateRootPaths.10 = YOURPATH" you can override the path.

I often use the "5" for default templates, because there are some "positiv positions" (0-4) under the default. There was once a usecase i think ;)

Regards,
Tim

**Comment by pniederlag** [comment]
Currently it's possible to inject/add some addiotional paths to the lookup with: "plugin.tx_autoloader.view.templateRootPaths.10 = YOURPATH"

However the default template will still be saved in the default path, if i am not mistaking. This way I end up with duplicates, which are likely to be confusing.

I'd just like to use something like:

theme_xxxx/Resources/Private/Templates/Content/
theme_xxxx/Resources/Private/Partials/Content/
theme_xxxx/Resources/Private/Layouts/Content/

within the scope of EXT:autoloader for my extension theme_xxxx in FE as well as in BE and for the default-files to be written to.

The top level folder shall be reserved for PAGE level related templates/partials/layouts.

**Comment by pniederlag** [comment]
just to give you an idea here's a patch I currently appy
[autoloader-add-path-Content-for-fluid.patch.txt](https://github.com/lochmueller/autoloader/files/2105956/autoloader-add-path-Content-for-fluid.patch.txt)

**Comment by pniederlag** [comment]
update: this is the patch as I do use it now. Note that I also changed the default backendLayout from 'Layouts/DefaultBackend.html' to 'Layouts/Content/DefaultBackend.html' ;)

[autoloader-add-path-Content-for-fluid.patch.txt](https://github.com/lochmueller/autoloader/files/2106026/autoloader-add-path-Content-for-fluid.patch.txt)

As said in our nice conversation, imho it would be cool if the autoloader would be enhanced in such a way that the paths by default could be changed by some simple configuration in order to match the approach that is part of the theming, where the fluid stuff for content elements always resides in a subpath 'Content/'. This give one location for all fluid stuff, while having a good separation between page related templates and content related elements.

Well, anyway, big thx for your openess and the effort you put into the autoloader. It's nice. :->

**Comment by lochmueller** [comment]
Hey @pniederlag 
first steps related to our call (take a look at the commits):
- https://github.com/lochmueller/autoloader/commit/2b9739b95cbb0ded4b3c45b77b7952b12549779a
- https://github.com/lochmueller/autoloader/commit/75a94c1a6f1136140b4e43fa037250c5dbf1b5dc
- https://github.com/lochmueller/autoloader/commit/098095b8373e584df0f437209a8ab5172619bc8d

Regards,
Tim

**Comment by lochmueller** [comment]
I close this issue. If there are still some problems, please report a new issue. Also the configuration via `tt_content.EXTKEY_CONTENTID.20.view` should be possible... Regards, Tim
