### ISSUE TITLE
Typo3 9.4.0 Error

### ISSUE THREAD

**Issue by mfMeds** [lochmueller/autoloader#120]
I installed your extension on Typo3 9.4.0 , but I get an error

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Class 'HDNET\Autoloader\Loader' not found | Error thrown in file /var/www/myProject.com/web/typo3conf/ext/autoloader/ext_localconf.php in line 12. Requested URL: http://myProject.com/typo3/index.php?route=%%2Fsystem%%2FBelogLog%%2F&token=--AnonymizedToken--`

can you fix this?

Thanks, 
Best regards!

**Comment by lochmueller** [comment]
@mfMeds Why the class is not found? Do you use composer based setup, right?

**Comment by mfMeds** [comment]
Sorry, I posted the wrong error. It was the problem with the removed reflection class. 
I see that you commited the fix.
