### ISSUE TITLE
Error in TCA loading

### ISSUE THREAD

**Issue by PascaleBeier** [lochmueller/autoloader#123]
see https://github.com/lochmueller/calendarize/issues/250

Steps to reproduce

- Run any upgrade wizard
- Check actual TCA in settings module

**Comment by lochmueller** [comment]
This problem is fixed in the 6.0.2 release. I moved the Doctrine Annotation registration to the loader class, so also the ModelUtility::getTcaInformation function can call the registration of "custom Annotations"
