### ISSUE TITLE
Error with version 6.0.2

### ISSUE THREAD

**Issue by Hobokens** [lochmueller/autoloader#124]
Hi Tim,
in my TYPO3 8.7.19 installation I get the appended error when trying to update vom v5.1. to 6.0.2.

Regards Hobokens

[error_autoloader_6.0.2.pdf](https://github.com/lochmueller/autoloader/files/2466216/error_autoloader_6.0.2.pdf)

**Comment by lochmueller** [comment]
Hey @Hobokens 
please delete all caches (via install tool or manually (typo3temp/var/)). This should fix this problem. There is no "Aspect" loader anymore and the RegisterAspect class is "old".
Regards,
Tim

**Comment by Hobokens** [comment]
Thanks for the quick reply, Tim.
I'm sorry, after deleting the whole folder 'typo3temp/var/' I get the appended error message. 
[autoloader_6.0.2._error_2.pdf](https://github.com/lochmueller/autoloader/files/2466321/autoloader_6.0.2._error_2.pdf)
I updated calendarize to version v4.0.1.
