### ISSUE TITLE
tx_calendarize_domain_model_event field description: htmlarea missing after update to autoloader 6.0.5

### ISSUE THREAD

**Issue by sdesign6** [lochmueller/autoloader#132]
There is an issue, after updating to autoloader 6.0.5.
The field "description" in tx_calendarize_domain_model_event is now single line without htmlarea with autoloader 6.0.5. With autoloader 4.0.1 everythings looking good.

TYPO3 Version 8.7.20
calendarize 4.0.1
autoloader 6.0.5 (before 4.0.1)

<img width="711" alt="bildschirmfoto 2018-11-14 um 16 35 52" src="https://user-images.githubusercontent.com/34130871/48493532-48a86280-e82c-11e8-9577-f9f39fcd6bba.png">
[HDNET_calendarize_21aaddceda_1.php.txt](https://github.com/lochmueller/autoloader/files/2581427/HDNET_calendarize_21aaddceda_1.php.txt)
[HDNET_calendarize_21aaddceda_2.php.txt](https://github.com/lochmueller/autoloader/files/2581428/HDNET_calendarize_21aaddceda_2.php.txt)

**Comment by charly83** [comment]
Is there already a solution? I have the same issue!

TYPO3 Version 8.7.22
calendarize 4.1.1
autoloader 6.0.5

**Comment by lochmueller** [comment]
Fixed in current master and next autoloader version 6.0.6
