### ISSUE TITLE
TYPO3 v9.5: VH <a:be.editLink /> otherwise all backend previews in page module are broken

### ISSUE THREAD

**Issue by josefglatz** [lochmueller/autoloader#134]
`Undeclared arguments passed to ViewHelper HDNET\Autoloader\ViewHelpers\Be\EditLinkViewHelper: data. Valid arguments are:`

The argument needs to be registered:

```
   public function initializeArguments()
    {
        $this->registerArgument('data', 'array', 'data', true, []);
    }
```

**Comment by lochmueller** [comment]
Thanks... fixed in current master. 👍
