### ISSUE TITLE
TYPO3 v9.5: "Check for broken Extensions" and other install tool modules fails

### ISSUE THREAD

**Issue by josefglatz** [lochmueller/autoloader#135]
I have the latest stable autoloader and one provider extension (ext:ccontent) where I use autoloader based content elements and lochmueller/faq.

I get a lot of PHP errors if I want to finalize the TYPO3 upgrade while
- trying the "Check for broken Extensions" install tool module
- trying the "Check TCA in ext_tables.php" install tool module
- trying to run the "Upgrade Wizard" install tool module to check whether there are any open upgrades or just to re-run upgrade wizards.

![image](https://user-images.githubusercontent.com/2861556/50902498-4ec95280-141b-11e9-82dc-90631870ee9b.png)

**There are multiple PHP errors thrown of the following error for example:**

`Wed, 09 Jan 2019 14:30:56 +0100 [CRITICAL] request="" component="TYPO3.CMS.Core.Error.DebugExceptionHandler": Core: Exception handler (WEB): Uncaught TYPO3 Exception: array_keys() expects parameter 1 to be array, null given | TypeError thrown in file /app/web/typo3conf/ext/autoloader/Classes/Loader/ContentObjects.php in line 407. Requested URL: http://projectname.docker/typo3/install.php?install[controller]=upgrade&install[context]=backend - {"TYPO3_MODE":"BE","exception":{"xdebug_message":"<tr><th align='left' bgcolor='#f57900' colspan=\"5\"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )<\/span> TypeError: array_keys() expects parameter 1 to be array, null given in \/app\/web\/typo3conf\/ext\/autoloader\/Classes\/Loader\/ContentObjects.php on line <i>407<\/i><\/th><\/tr>\n<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack<\/th><\/tr>\n<tr><th align='center' bgcolor='#eeeeec'>#<\/th><th align='left' bgcolor='#eeeeec'>Time<\/th><th align='left' bgcolor='#eeeeec'>Memory<\/th><th align='left' bgcolor='#eeeeec'>Function<\/th><th align='left' bgcolor='#eeeeec'>Location<\/th><\/tr>\n<tr><td bgcolor='#eeeeec' align='center'>1<\/td><td bgcolor='#eeeeec' align='center'>0.0114<\/td><td bgcolor='#eeeeec' align='right'>408192<\/td><td bgcolor='#eeeeec'>{main}(  )<\/td><td title='\/app\/web\/typo3\/install.php' bgcolor='#eeeeec'>...\/install.php<b>:<\/b>0<\/td><\/tr>\n<tr><td bgcolor='#eeeeec' align='center'>2<\/td><td bgcolor='#eeeeec' align='center'>0.0114<\/td><td bgcolor='#eeeeec' align='right'>408512<\/td><td bgcolor='#eeeeec'>{closure:\/app\/web\/typo3\/install.php:101-105}(  )<\/td><td title='\/app\/web\/typo3\/install.php' bgcolor='#eeeeec'>...\/install.php<b>:<\/b>105<\/td><\/tr>\n<tr><td bgcolor='#eeeeec' align='center'>3<\/td><td bgcolor='#eeeeec' align='center'>1.2179<\/td><td bgcolor='#eeeeec' align='right'>1347544<\/td><td bgcolor='#eeeeec'>TYPO3\\CMS\\Install\\Http\\Application->run(  )<\/td><td title='\/app\/web\/typo3\/install.php' bgcolor='#eeeeec'>...\/install.php<b>:<\/b>104<\/td><\/tr>\n<tr><td bgcolor='#eeeeec' align='center'>4<\/td><td bgcolor='#eeeeec' align='center'>1.2746<\/td><td bgcolor='#eeeeec' align='right'>1439912<\/td><td bgcolor='#eeeeec'>TYPO3\\CMS\\Install\\Http\\Application->handle(  )<\/td><td title='\/app\/web\/typo3\/sysext\/core\/Classes\/Http\/AbstractApplication.php' bgcolor='#eeeeec'>...\/AbstractApplication.php<b>:<\/b>110<\/td><\/tr>\n<tr><td bgcolor='#eeeeec' align='center'>5<\/td><td bgcolor='#eeeeec' align='center'>1.2802<\/td><td bgcolor='#eeeeec' align='right'>1448728<\/td><td bgcolor='#eeeeec'>TYPO3\\CMS\\Install\\Http\\RequestHandler->handle(  )<\/td><td title='\/app\/web\/typo3\/sysext\/install\/Classes\/Http\/Application.php' bgcolor='#eeeeec'>...\/Application.php<b>:<\/b>65<\/td><\/tr>\n<tr><td bgcolor='#eeeeec' align='center'>6<\/td><td bgcolor='#eeeeec' align='center'>1.2882<\/td><td bgcolor='#eeeeec' align='right'>1528576<\/td><td bgcolor='#eeeeec'>TYPO3\\CMS\\Install\\Controller\\UpgradeController->extensionCompatTesterLoadExtTablesAction(  )<\/td><td title='\/app\/web\/typo3\/sysext\/install\/Classes\/Http\/RequestHandler.php' bgcolor='#eeeeec'>...\/RequestHandler.php<b>:<\/b>205<\/td><\/tr>\n<tr><td bgcolor='#eeeeec' align='center'>7<\/td><td bgcolor='#eeeeec' align='center'>1.5250<\/td><td bgcolor='#eeeeec' align='right'>2803984<\/td><td bgcolor='#eeeeec'>TYPO3\\CMS\\Install\\Controller\\UpgradeController->extensionCompatTesterLoadExtLocalconfForExtension(  )<\/td><td title='\/app\/web\/typo3\/sysext\/install\/Classes\/Controller\/UpgradeController.php' bgcolor='#eeeeec'>...\/UpgradeController.php<b>:<\/b>425<\/td><\/tr>\n<tr><td bgcolor='#eeeeec' align='center'>8<\/td><td bgcolor='#eeeeec' align='center'>1.5254<\/td><td bgcolor='#eeeeec' align='right'>2804400<\/td><td bgcolor='#eeeeec'>require( <font color='#00bb00'>'\/app\/web\/typo3conf\/ext\/ccontent\/ext_localconf.php'<\/font> )<\/td><td title='\/app\/web\/typo3\/sysext\/install\/Classes\/Controller\/UpgradeController.php' bgcolor='#eeeeec'>...\/UpgradeController.php<b>:<\/b>1126<\/td><\/tr>\n<tr><td bgcolor='#eeeeec' align='center'>9<\/td><td bgcolor='#eeeeec' align='center'>2.3697<\/td><td bgcolor='#eeeeec' align='right'>3954024<\/td><td bgcolor='#eeeeec'>HDNET\\Autoloader\\Loader::extTables(  )<\/td><td title='\/app\/web\/typo3conf\/ext\/ccontent\/ext_localconf.php' bgcolor='#eeeeec'>...\/ext_localconf.php<b>:<\/b>12<\/td><\/tr>\n<tr><td bgcolor='#eeeeec' align='center'>10<\/td><td bgcolor='#eeeeec' align='center'>2.3697<\/td><td bgcolor='#eeeeec' align='right'>3954024<\/td><td bgcolor='#eeeeec'>HDNET\\Autoloader\\Loader->loadExtTables(  )<\/td><td title='\/app\/web\/typo3conf\/ext\/autoloader\/Classes\/Loader.php' bgcolor='#eeeeec'>...\/Loader.php<b>:<\/b>124<\/td><\/tr>\n<tr><td bgcolor='#eeeeec' align='center'>11<\/td><td bgcolor='#eeeeec' align='center'>2.3697<\/td><td bgcolor='#eeeeec' align='right'>3954400<\/td><td bgcolor='#eeeeec'>HDNET\\Autoloader\\Loader->prepareAutoLoaderObjects(  )<\/td><td title='\/app\/web\/typo3conf\/ext\/autoloader\/Classes\/Loader.php' bgcolor='#eeeeec'>...\/Loader.php<b>:<\/b>186<\/td><\/tr>\n<tr><td bgcolor='#eeeeec' align='center'>12<\/td><td bgcolor='#eeeeec' align='center'>2.3698<\/td><td bgcolor='#eeeeec' align='right'>3954456<\/td><td bgcolor='#eeeeec'>HDNET\\Autoloader\\Loader->buildLoaderInformation(  )<\/td><td title='\/app\/web\/typo3conf\/ext\/autoloader\/Classes\/Loader.php' bgcolor='#eeeeec'>...\/Loader.php<b>:<\/b>325<\/td><\/tr>\n<tr><td bgcolor='#eeeeec' align='center'>13<\/td><td bgcolor='#eeeeec' align='center'>2.4395<\/td><td bgcolor='#eeeeec' align='right'>3956472<\/td><td bgcolor='#eeeeec'>HDNET\\Autoloader\\Loader\\ContentObjects->prepareLoader(  )<\/td><td title='\/app\/web\/typo3conf\/ext\/autoloader\/Classes\/Loader.php' bgcolor='#eeeeec'>...\/Loader.php<b>:<\/b>344<\/td><\/tr>\n<tr><td bgcolor='#eeeeec' align='center'>14<\/td><td bgcolor='#eeeeec' align='center'>2.4993<\/td><td bgcolor='#eeeeec' align='right'>3959552<\/td><td bgcolor='#eeeeec'>HDNET\\Autoloader\\Loader\\ContentObjects->getDefaultTcaFields(  )<\/td><td title='\/app\/web\/typo3conf\/ext\/autoloader\/Classes\/Loader\/ContentObjects.php' bgcolor='#eeeeec'>...\/ContentObjects.php<b>:<\/b>79<\/td><\/tr>\n<tr><td bgcolor='#eeeeec' align='center'>15<\/td><td bgcolor='#eeeeec' align='center'>2.4994<\/td><td bgcolor='#eeeeec' align='right'>3960448<\/td><td bgcolor='#eeeeec'><a href='http:\/\/www.php.net\/function.array-keys' target='_new'>array_keys<\/a>\n(  )<\/td><td title='\/app\/web\/typo3conf\/ext\/autoloader\/Classes\/Loader\/ContentObjects.php' bgcolor='#eeeeec'>...\/ContentObjects.php<b>:<\/b>407<\/td><\/tr>\n"}}`

**Comment by lochmueller** [comment]
Hey @josefglatz 
Seems, that the Install tool check to not build the complete TCA. I fixed this error and I hope there are no following errors...
Regards, Tim
