### ISSUE TITLE
TYPO3 v9.5: TCA Migrations: TCA configuration needs to be adjusted

### ISSUE THREAD

**Issue by josefglatz** [lochmueller/autoloader#136]
When I use autoloader based extensions (I actually only use it for content elements and ext:faq) some adoptions according to TCA must be done to prevent filling up log files of TYPO3.

**Following deprecation messages are thrown in TYPO3 v9.5:**

`Thu, 10 Jan 2019 09:12:00 +0100 [NOTICE] request="8fe72a53b92e0" component="TYPO3.CMS.deprecations": Core: Error handler (BE): TYPO3 Deprecation Notice: Automatic TCA migration done during bootstrap. Please adapt TCA accordingly, these migrations will be removed. The backend module "Configuration -> TCA" shows the modified values. Please adapt these areas:
RTE configuration via 'defaultExtras' options are deprecated. String "richtext:rte_transform[flag=rte_enabled|mode=ts_css]" in TCA tx_faq_domain_model_question['columns']['answer']['defaultExtras'] was changed to options in tx_faq_domain_model_question['columns']['answer']['config']`

---

`Thu, 10 Jan 2019 09:12:00 +0100 [NOTICE] request="8fe72a53b92e0" component="TYPO3.CMS.deprecations": Core: Error handler (BE): TYPO3 Deprecation Notice: Property HDNET\Faq\Domain\Model\Questioncategory::parent is tagged with @lazy which is deprecated and will be removed in TYPO3 v10.0. in /app/web/typo3/sysext/extbase/Classes/Reflection/ClassSchema.php line 256`

---

`Thu, 10 Jan 2019 09:12:00 +0100 [NOTICE] request="8fe72a53b92e0" component="TYPO3.CMS.deprecations": Core: Error handler (BE): TYPO3 Deprecation Notice: Usage of TYPO3\CMS\Core\Cache\CacheManager->createCache('autoloader') in ext_localconf.php will not be supported in TYPO3 v10.0. in /app/web/typo3/sysext/core/Classes/Cache/CacheManager.php line 285`

---

`Thu, 10 Jan 2019 09:12:00 +0100 [NOTICE] request="8fe72a53b92e0" component="TYPO3.CMS.deprecations": Core: Error handler (BE): TYPO3 Deprecation Notice: Usage of TYPO3\CMS\Core\Cache\CacheManager->createCache('extbase_reflection') in ext_localconf.php will not be supported in TYPO3 v10.0. in /app/web/typo3/sysext/core/Classes/Cache/CacheManager.php line 285`

---

**Massive amount of** `Thu, 10 Jan 2019 09:06:58 +0100 [NOTICE] request="73f4bac75069f" component="TYPO3.CMS.deprecations": Core: Error handler (BE): TYPO3 Deprecation Notice: Method TYPO3\CMS\Extbase\Reflection\ReflectionService::getClassTagValues is deprecated and will be removed in TYPO3 v10.0. in /app/web/typo3/sysext/extbase/Classes/Reflection/ReflectionService.php line 116`

and

`Thu, 10 Jan 2019 09:12:00 +0100 [NOTICE] request="8fe72a53b92e0" component="TYPO3.CMS.deprecations": Core: Error handler (BE): TYPO3 Deprecation Notice: Method TYPO3\CMS\Extbase\Reflection\ReflectionService::getMethodTagsValues is deprecated and will be removed in TYPO3 v10.0. in /app/web/typo3/sysext/extbase/Classes/Reflection/ReflectionService.php line 204`

**Comment by lochmueller** [comment]
The "createCache" problems are not part of autoloader. The EXT:faq problem is fixed in the FAQ extension (current git).

Still open is:
```Thu, 10 Jan 2019 09:12:00 +0100 [NOTICE] request="8fe72a53b92e0" component="TYPO3.CMS.deprecations": Core: Error handler (BE): TYPO3 Deprecation Notice: Automatic TCA migration done during bootstrap. Please adapt TCA accordingly, these migrations will be removed. The backend module "Configuration -> TCA" shows the modified values. Please adapt these areas: RTE configuration via 'defaultExtras' options are deprecated. String "richtext:rte_transform[flag=rte_enabled|mode=ts_css]" in TCA tx_faq_domain_model_question['columns']['answer']['defaultExtras'] was changed to options in tx_faq_domain_model_question['columns']['answer']['config']```

```Thu, 10 Jan 2019 09:06:58 +0100 [NOTICE] request="73f4bac75069f" component="TYPO3.CMS.deprecations": Core: Error handler (BE): TYPO3 Deprecation Notice: Method TYPO3\CMS\Extbase\Reflection\ReflectionService::getClassTagValues is deprecated and will be removed in TYPO3 v10.0. in /app/web/typo3/sysext/extbase/Classes/Reflection/ReflectionService.php line 116```

```Thu, 10 Jan 2019 09:12:00 +0100 [NOTICE] request="8fe72a53b92e0" component="TYPO3.CMS.deprecations": Core: Error handler (BE): TYPO3 Deprecation Notice: Method TYPO3\CMS\Extbase\Reflection\ReflectionService::getMethodTagsValues is deprecated and will be removed in TYPO3 v10.0. in /app/web/typo3/sysext/extbase/Classes/Reflection/ReflectionService.php line 204```
