### ISSUE TITLE
[BUG] Could not load layout file. (TYPO3 6.2 only problem?)

### ISSUE THREAD

**Issue by jousch** [lochmueller/autoloader#15]
Hey,

I'm getting exceptions for the page module previews, since the ext:autoloader generates automatically the layout files.

```
#1288092555: Could not load layout file. Tried following paths: "typo3conf/ext/provider/Resources/Private/Layouts/ContentBackend.html", "typo3conf/ext/provider/Resources/Private/Layouts/ContentBackend". (http://typo3.org/go/exception/CMS/debug/1288092555)

TYPO3\CMS\Fluid\View\Exception\InvalidTemplateResourceException thrown in file
/docker/code/typo3_src-6.2.15/typo3/sysext/fluid/Classes/View/StandaloneView.php in line 410.
```

---

**My actual workaround**
Don't using a layout for backend previews. 😢

**Comment by lochmueller** [comment]
Can you reproduce the mistake? I saw the error once and can not reproduce it... Is the file-path right? Is there a valid Layout file?

**Comment by jousch** [comment]
Yeah, I could reproduce it. I appears in two 6.2.15 installations.

**Comment by jousch** [comment]
The file is here. I will xdebug tomorrow. Maybe I get some more insights

**Comment by lochmueller** [comment]
Hey @jousch Do you debug the problem? Any news for me to fix this issue?

**Comment by jousch** [comment]
I've tried but without any solution. Alex could also reproduce it. @lochmueller could you reproduce the error?

**Comment by jousch** [comment]
I will take a look once more the next few days

**Comment by lochmueller** [comment]
No... I directly fix it. I have no 6.2 dev system anymore at the moment... ;)

**Comment by lochmueller** [comment]
Sorry... wrong ticket. Of cource I do not fix anything at the moment :)

**Comment by jousch** [comment]
Alex found it. Will come up with an pull request tomorrow!

**Comment by lochmueller** [comment]
Hey @jousch any news on this topic?
