### ISSUE TITLE
Breaking Change: Extbase persistence configuration

### ISSUE THREAD

**Issue by dustinjeuck** [lochmueller/autoloader#153]
Since Typo3 10.0 it is not longer possible to override the table names of an extbase model by using TypoScript (tx_extbase.persistence...).

In the future, a new configuration file (Configuration/Extbase/Persistence/Classes.php) is required.

See:
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87623-ReplaceConfigpersistenceclassesTyposcriptConfiguration.html

**Comment by lochmueller** [comment]
Hey @dustinjeuck ,
you can use this in the next version:
```
<?php
declare(strict_types=1);

return \HDNET\Autoloader\Utility\ExtbasePersistenceUtility::getClassMappingForExtension('YOUR_EXTENSION_KEY');
```
Regards,
Tim
