### ISSUE TITLE
Create "sorting" Column in AbstractSimpleRelation.php

### ISSUE THREAD

**Issue by Jaiprucl** [lochmueller/autoloader#155]
There is no need to create a "sorting" column in AbstractSimpleRelation.php sind TYPO3 9.3 because the core will automatically add the column. 
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.3/Feature-85160-AutoCreateManagementDBFieldsFromTCACtrl.html

**Comment by lochmueller** [comment]
Hey @Jaiprucl 
thanks for the hint. For the sorting in AbstractSimpleRelation it is not so easy, because I need the mapping. But I reduce the amount of SQL for all the other tables.
Regards,
Tim
