### ISSUE TITLE
calendarize + autoloader + typo3-console: No valid mapper for the given type found

### ISSUE THREAD

**Issue by wazum** [lochmueller/autoloader#156]
When I try to use `"lochmueller/calendarize": "dev-master"` (TYPO3 10.4.6) with `"helhum/typo3-console": "6.3.2"` I get the following exceptions using `database:updateschema` or others (see below):

```
> ./typo3cms database:updateschema "*.add" || true

  [ HDNET\Autoloader\Exception ]
  No valid mapper for the given type found:

database:updateschema [--dry-run] [--] [<schemaUpdateTypes>]

> ./typo3cms extension:setupactive || true

  [ HDNET\Autoloader\Exception ]
  No valid mapper for the given type found:
```

**Comment by lochmueller** [comment]
Cannot rebuild this problem with  the current master of EXT:autoloader. I will push a new release...

**Comment by lochmueller** [comment]
hey @wazum ,
I created a more detailed exception (incl. Model, Property and error) in case of this exception. Please rerun your test with the current EXT:autoloader dev-master or next release.
Regards,
Tim
