### ISSUE TITLE
Deprecated $GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']

### ISSUE THREAD

**Issue by webian** [lochmueller/autoloader#158]
In TYPO3 10, deprecation of $GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf'] probably affect also this code:
https://github.com/lochmueller/autoloader/blob/08609dec38efb12fd51e76f1b272cdbfdcb46e82/Classes/SmartObjectManager.php#L126

But I didn't debug so I'm not sure if it's used or not.
Please note that there are other places that use $GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf'].

**Comment by webian** [comment]
See: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.0/Deprecation-82254-DeprecateGLOBALSTYPO3_CONF_VARSEXTextConf.html

**Comment by lochmueller** [comment]
Thanks for reporting. Fixed in current master.
