### ISSUE TITLE
Deprecated TSFE:sys_language_uid

### ISSUE THREAD

**Issue by webian** [lochmueller/autoloader#159]
Hi, I'm not sure it it affects this but, for TYPO3 10 LTS, `TSFE:sys_language_uid` must be `sitelanguage:languageId`

https://github.com/lochmueller/autoloader/blob/93a87e476fecf347fa82cde35d128444815dde8d/Configuration/TypoScript/BackendLayouts/setup.txt#L17

**Comment by lochmueller** [comment]
Thanks for reporting. Fixed in ccurrent master and next release.
