### ISSUE TITLE
Wrong type for sorting_foreign field 

### ISSUE THREAD

**Issue by webian** [lochmueller/autoloader#163]
Hi!
I guess that here: https://github.com/lochmueller/autoloader/blob/ab0d842e066ff268ae7780d81f1b991259605649/Classes/Domain/Model/AbstractAdvancedRelation.php#L32
it should be `@DatabaseField(type="int")` not string or else the sorting_foreign field will be of type `text` and sorting will be made alphabetically:
- 1
- 10
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9

instead of:

- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10

**Comment by lochmueller** [comment]
Hey @webian 
You are right. Thanks for reporting.... fixed in current master.
Regards,
Tim
