### ISSUE TITLE
Table 'typo3.tt_conten' doesn't exist

### ISSUE THREAD

**Issue by rabe69** [lochmueller/autoloader#17]
I don't know why, but if I use the content object functionality of autoloader with the 6.2.14 version of TYPO3, I got this SQL-Error in Front- and Backend.

After some debugging, I notice that inside the dynamic generated typoscript from autoloader the last "t" of "tt_content" is missing.

If I look in Classes/Loader/ContentObjects.php at line 345, everything looks good for me.
```
config.tx_extbase.persistence.classes.' . $config['modelClass'] . '.mapping.tableName = tt_content');
```
But if I look at the generated typoscript, it looks like this:
```
config.tx_extbase.persistence.classes.VENDOR\ExtKey\Domain\Model\Content\MyContent.mapping.tableName = tt_conten
```
Adding a linebreak at the end of Classes/Loader/ContentObjects.php line 345 solve this problem:
```
config.tx_extbase.persistence.classes.' . $config['modelClass'] . '.mapping.tableName = tt_content
');
```

**Comment by lochmueller** [comment]
Hey Alex, thanks for the report... I add the break to the current master.

**Comment by jousch** [comment]
Couldn't reproduce it with TYPO3 6.2.15 and autoloader 1.9.4 typo3-ter.
