### ISSUE TITLE
Exception during backend login after updating autoloader from 7.2.2 to 7.2.3

### ISSUE THREAD

**Issue by mediaessenz** [lochmueller/autoloader#173]
(1/1) TypeError

Return value of TYPO3\CMS\Extbase\Utility\LocalizationUtility::getLanguageService() must be an instance of TYPO3\CMS\Core\Localization\LanguageService, null returned

Used plattform: latest TYPO3 10.4

Used this static method in a TCA definition, which is the cause of the exception, I think:
\HDNET\Autoloader\Utility\TranslateUtility::getLll('languagekey, 'extensionkey')

**Comment by lochmueller** [comment]
Hey @mediaessenz 
this is already fixed by comment out "old" code:
https://github.com/lochmueller/autoloader/commit/c05290e09db7375666836b83ae176eafde23c1a1
I pushed version 7.2.4 to TER.
Regards,
Tim
