### ISSUE TITLE
TYPO3 11 and PHP 8 - PHP Warning: Undefined array key "autoloader"

### ISSUE THREAD

**Issue by dev-stefan** [lochmueller/autoloader#174]
When using the autoloader extension with PHP 8 I receive the following PHP Warning due to PHP strict mode.
The error occurs while trying to load a backend layout.
The TYPO3 instance cannot be used with having this issue.

(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined array key "autoloader" in /var/www/html/public/typo3conf/ext/autoloader/Classes/Utility/TranslateUtility.php line 39

in /var/www/html/public/typo3/sysext/core/Classes/Error/ErrorHandler.php line 145
        }

        $message = self::ERROR_LEVEL_LABELS[$errorLevel] . ': ' . $errorMessage . ' in ' . $errorFile . ' line ' . $errorLine;
        if ($errorLevel & $this->exceptionalErrors) {
            throw new Exception($message, 1476107295);
        }

        $message = $this->getFormattedLogMessage($message);

at TYPO3\CMS\Core\Error\ErrorHandler->handleError(2, 'Undefined array key "autoloader"', '/var/www/html/public/typo3conf/ext/autoloader/Classes/Utility/TranslateUtility.php', 39)
in /var/www/html/public/typo3conf/ext/autoloader/Classes/Utility/TranslateUtility.php line 39
     * @return string
     */
    public static function assureLabel($key, $extensionName, $default = null, $arguments = null, $tableName = null)
    {
        if (\is_array($GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['autoloader']['assureLabel'])) {
            foreach ($GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['autoloader']['assureLabel'] as $classConfig) {
                $object = GeneralUtility::makeInstance($classConfig);
                if (\is_object($object) && method_exists($object, 'assureLabel')) {
                    $object->assureLabel($key, $extensionName, $default, $arguments, $tableName);

at HDNET\Autoloader\Utility\TranslateUtility::assureLabel('backendLayout.Home.txt', 'website', 'Home')
in /var/www/html/public/typo3conf/ext/autoloader/Classes/Loader/BackendLayout.php line 43
            $extension = IconUtility::getIconFileExtension(GeneralUtility::getFileAbsFileName($iconPath));

            $translationKey = 'backendLayout.'.$pathInfo['basename'];
            if (LoaderInterface::EXT_TABLES === $type) {
                TranslateUtility::assureLabel($translationKey, $loader->getExtensionKey(), $pathInfo['filename']);
            }
            $backendLayouts[] = [
                'path' => 'EXT:'.$loader->getExtensionKey().'/Resources/Private/BackendLayouts/'.$file,
                'filename' => $pathInfo['filename'],

**Comment by lochmueller** [comment]
Thanks for reporting this warning. Fixed in current master.
