### ISSUE TITLE
PHP 8.0 Warnings 

### ISSUE THREAD

**Issue by mediaessenz** [lochmueller/autoloader#179]
1.  Warning: Undefined array key "shadowColumnsForNewPlaceholders" in /typo3conf/ext/autoloader/Classes/Service/SmartObjectInformationService.php line 159
2. Warning: Attempt to read property "argumentName" on null in /app/private/typo3conf/ext/autoloader/Classes/Loader/Slots.php line 58

PR is following ...

**Comment by lochmueller** [comment]
Thanks for the PR.
