### ISSUE TITLE
icons of content objects not loaded in backend under 6.2

### ISSUE THREAD

**Issue by rabe69** [lochmueller/autoloader#18]
After some debugging I found a solution:
Change this in /Classes/Loader/ContentObjects.php line 263:
```
SpriteManager::addTcaTypeIcon('tt_content', $typeKey, str_replace('../', '', $icon));
```
to this:
```
SpriteManager::addTcaTypeIcon('tt_content', $typeKey, str_replace('../typo3/', '', $icon));
```

May be this path must be different under 7.x. In this case a condition will help.

**Comment by lochmueller** [comment]
Does this patch solve the problem also for 6.2: https://github.com/lochmueller/autoloader/commit/2e74aae39262148ddd82745b95dafc54c39174ce

**Comment by rabe69** [comment]
No, because static method getAbsoluteWebPath does not exists under 6.2

**Comment by lochmueller** [comment]
OK... next try ;) https://github.com/lochmueller/autoloader/commit/1b3b77f835a6518d8068365cd05585d5bad1891d I add a condition with your solution for TYPO3 < 7.0
