### ISSUE TITLE
$GLOBALS array cannot be passed by reference since PHP 8.1

### ISSUE THREAD

**Issue by svewap** [lochmueller/autoloader#183]
This leads to the following error:

`HDNET\Autoloader\Utility\ArrayUtility::setNodes(): Argument #2 ($array) cannot be passed by reference`

Since the GLOBALS variable cannot be completely overwritten, a return $GLOBALS will not work. A direct modification of the variable will probably be necessary.

**Comment by lochmueller** [comment]
Hey @svewap 

Do you check the calling part of the Problem? Is it EXT:autoloader/Classes/Utility/ExtendedUtility.php Line 105?
Could you check a solution? Like drop the first element from $location and Assign $GLOBALS[$firstElement] to the method?

Regards,
Tim

**Comment by svewap** [comment]
Hi Tim,
> Do you check the calling part of the Problem? Is it EXT:autoloader/Classes/Utility/ExtendedUtility.php Line 105? 

exactly

> Could you check a solution? Like drop the first element from $location and Assign $GLOBALS[$firstElement] to the method?

The solution will be to construct a special method that is there exclusively to modify the $GLOBALS variable, because you won't be able to pass the $GLOBALS variable by reference anymore. And passing it to a helper function without reference doesn't make sense either, because a return won't work. So the only way I see is to use a separate helper function that directly accesses the $GLOBALS variable.
