### ISSUE TITLE
New Installation runs into many errors

### ISSUE THREAD

**Issue by LeonEmm** [lochmueller/autoloader#184]
Hello everybody,
i have a big issue with my typo3 installation:

After  I installed according to the readme, many errors occured:
![image](https://user-images.githubusercontent.com/93478428/159570200-d651e920-b217-45c4-a380-41d5077d5ff7.png)

I have no idea why they occur and how to solve them. I'm running typo3 with the latest versions available.

Thanks for your help

**Comment by lochmueller** [comment]
Hey @LeonEmm 

I think a few PHP Warnings (these are no fatal, no errors) are not a "big issue" :) 
But... the problem is already fixed: https://github.com/lochmueller/autoloader/commit/938592f4cbf62fc1ff328acddd52edc7c95f91f0

I will push a new release of EXT:autoloader today.

Regards,
Tim
