### ISSUE TITLE
Error after update to TYPO3 10 in autoloader 7.3.5

### ISSUE THREAD

**Issue by maximaexchen** [lochmueller/autoloader#186]
On Extension activation I get following error:

[Semantical Error] The annotation "@hook" in class HDNET\Autoloader\Hooks\ClearCache was never imported. Did you maybe forget to add a "use" statement for this annotation?

**Comment by lochmueller** [comment]
Hey @maximaexchen 
there is no such file in the version: https://github.com/lochmueller/autoloader/tree/7.3.5/Classes/Hooks
Do you update from an old version to a new one? I suggest dropping all caches of TYPO3 and perhaps the autoloader_* Cache files manually.
Regards,
Tim
