### ISSUE TITLE
Add locallang/language override loader

### ISSUE THREAD

**Issue by mbrodala** [lochmueller/autoloader#19]
It would be nice to have a autoloader for locallang/language overrides.

Normally one must add something like this in the `ext_localconf.php`:

```php
$TYPO3_CONF_VARS['SYS']['locallangXMLOverride']['default']['EXT:foo/Resources/Private/Language/locallang.xlf'][] = 'EXT:bar/Resources/Private/Language/Path/To/Foo/locallang.xlf';

$TYPO3_CONF_VARS['SYS']['locallangXMLOverride']['de']['EXT:foo/Resources/Private/Language/locallang.xlf'][] = 'EXT:bar/Resources/Private/Language/Path/To/Foo/de.locallang.xlf';
```

I'd suggest that language overrides must be placed in `Resources/Private/Language/Overrides/ExtensionName/original/path/to/locallang.xlf`.

With this, the loader could deduce the extension name via `GeneralUtility::camelCaseToLowerCaseUnderscored()` and use the path after `Resources/Private/Language/Overrides/ExtensionName/` for the original file path. The language key could be taken from the file prefix of XLIFF files. Examples:

* `Resources/Private/Language/Overrides/FooBar/mod1/locallang_mod.xlf` yields 
  `$TYPO3_CONF_VARS['SYS']['locallangXMLOverride']['default']['EXT:foo_bar/mod1/locallang_mod.xlf'][] = 'EXT:my_extension/Resources/Private/Language/Overrides/FooBar/mod1/locallang_mod.xlf';`
* `Resources/Private/Language/Overrides/FooBar/mod1/de.locallang_mod.xlf` yields 
  `$TYPO3_CONF_VARS['SYS']['locallangXMLOverride']['de']['EXT:foo_bar/mod1/locallang_mod.xlf'][] = 'EXT:my_extension/Resources/Private/Language/Overrides/FooBar/mod1/de.locallang_mod.xlf';`
* `Resources/Private/Language/Overrides/Qux/Resources/Private/Language/locallang.xlf` yields 
  `$TYPO3_CONF_VARS['SYS']['locallangXMLOverride']['de']['EXT:qux/Resources/Private/Language/locallang.xlf'][] = 'EXT:my_extension/Resources/Private/Language/Overrides/Qux/Resources/Private/Language/locallang.xlf';`

It could be argued that the last example is unnecessarily verbose but it should be this way for consistency. If at one point in the future every extension sticks to `Resources/Private/Language`, this could be simplified a lot.

**Comment by lochmueller** [comment]
Hey @mbrodala 

great idea. I will implement a loader shortly (in the next days). 
Thanks for the feedback and detailed description of this feature.

Regards,
Tim

**Comment by mbrodala** [comment]
Damn, your're quick. :-) I just fixed some errors in the description.

**Comment by lochmueller** [comment]
Hey @mbrodala 
please take a look at the first version of your idea:
https://github.com/lochmueller/autoloader/commit/ca0885f16a127f239553296add34681a489943d4

Any suggestions, fixes etc.?

Regards,
Tim

**Comment by mbrodala** [comment]
Looks damn good on a first glimpse.

AFAIS overrides for non-`default` languages will only be possible with XLIFF by default since the support for locallang and php would require actual parsing of the translation files.

I'll try to perform a functional test today and let you know.

**Comment by mbrodala** [comment]
Found [a bug](https://github.com/lochmueller/autoloader/commit/ca0885f16a127f239553296add34681a489943d4#commitcomment-14236428)

**Comment by lochmueller** [comment]
So... fix the open comments. If there are still errors in the current master, please create a new issue.

**Comment by mbrodala** [comment]
Works like a charm, thanks. :-)
