### ISSUE TITLE
Input fields of content elements not visible

### ISSUE THREAD

**Issue by mediaessenz** [lochmueller/autoloader#193]
I have a strange behaviour with a page, where I used autoloaders content element loader.
In the beginning everything works fine, and all fields I defined in my model also apear in the content element as input.
e.g. this model config adds a simple input field in the corresponding content element:
```php
/**
 * Yalawo element
 *
 * @author     Alexander Grein <alexander.grein@gmail.com>
 * @DatabaseTable("tt_content")
 * @WizardTab("special")
 * @NoHeader
 */
class Yolawo extends AbstractEntity {

	/**
	 * @var string
     * @DatabaseField("string")
	 */
	protected $yolawoId;

	/**
	 * @return string
	 */
	public function getYolawoId() {
		return $this->yolawoId;
	}

	/**
	 * @param string $yolawoId
	 */
	public function setYolawoId($yolawoId) {
		$this->yolawoId = $yolawoId;
	}

}
```
But now, I do not know the reason, because I did not changed anything in the model or other related paths, the content element shows all "normal" field of a content (with header), but the field ("yolowa_id" in the example) from the model doesn't apear anymore.

If I look in the TCA-Explorer, there is also no model related definition in the type :
```
--div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:general, --palette--;;general, --palette--;;headers, --div--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:tabs.appearance, --palette--;;frames, --palette--;;appearanceLinks, --div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:language, --palette--;;language, --div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:access, --palette--;;hidden, --palette--;;access, --div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:categories, categories, --div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:notes, rowDescription, --div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:extended,
```

One time, after several deployments, the TCA of the type definition suddenly changed and the definition contained the 'yolawo_id' field. But this happens only one time. After another deployment I got the wrong TCA-definition again.

My system:
TYPO3 11.5.19 (just updated from 11.5.18, but same problem)
PHP 8.1.10
EXT:autoloader 7.3.7

**Comment by mediaessenz** [comment]
I think I found the reason.

It's line 177 in the Loader/ContentObject class:
```php
if (!isset($GLOBALS['TCA']['tt_content']['types'][$typeKey]['showitem']) || empty($GLOBALS['TCA']['tt_content']['types'][$typeKey]['showitem'])) {
```
In the beginning, this key doesn't exists:
```
$GLOBALS['TCA']['tt_content']['types'][$typeKey]
```
which throws an exception on my system. 

Because of this, the enclosed block is not executed, which is responsible to add the types configuration of the content element.

**Comment by mediaessenz** [comment]
After some further debugging, I found out, that the array key is already filled at the time of calling with the following:
```
                --div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:general,
                    --palette--;;general,
                    --palette--;;headers,
                --div--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:tabs.appearance,
                    --palette--;;frames,
                    --palette--;;appearanceLinks,
                --div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:language,
                    --palette--;;language,
                --div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:access,
                    --palette--;;hidden,
                    --palette--;;access,
                --div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:categories,
                    categories,
                --div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:notes,
                    rowDescription,
                --div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:extended,
```
For this reason, the condition is not met and the fields of the content element are not added.

**Comment by lochmueller** [comment]
Hey @mediaessenz 
No EXT:autoloader always write the type configuration and I add a configuration to keep the original (if needed). I think the problem is related to 11.5.18&11.5.19, but I don't found any clue in the release notes. So it is fixed in EXT:autoloader.
Will publish a new release in a few seconds.
Regards,
Tim

**Comment by mediaessenz** [comment]
I really don't understand what the noAutoloaderOverride key is all about?
Since this key never exists, because it is not set anywhere, the condition will be always true.

**Comment by lochmueller** [comment]
Hey @mediaessenz 

Before the condition check, if someone else created a TCA configuration and EXT:autoloader do not touch this configuration. The "noAutoloaderOverride" option take care of this now. You can create a TCA configuration in front of the EXT:autoloader manually and if you set "noAutoloaderOverride" the EXT:autoloader do not touch this configuration.

Yes... if you're not use this feature, the key does not exist and the condition is always true in your context.

Regards,
Tim
