### ISSUE TITLE
The latest version 7.3.8 is available via Composer, but not via Extension Manager

### ISSUE THREAD

**Issue by sypets** [lochmueller/autoloader#194]
* tags: https://github.com/lochmueller/autoloader/tags
* TER: https://extensions.typo3.org/extension/autoloader

**Comment by lochmueller** [comment]
Hey @sypets 

some miss configuration in the actions. 
Actions run again: https://github.com/lochmueller/autoloader/actions/runs/3712030441/jobs/6293105466

Version 7.3.9 should be visible in TER in the next minutes

Regards,
Tim
