### ISSUE TITLE
"Undefined array key" on composer install (TYPO3 11, PHP 8.0)

### ISSUE THREAD

**Issue by lorisnico2000** [lochmueller/autoloader#197]
I get this error on first composer install, because in php 8 "Undefined array key" is now a warning:
```
Warning: Undefined array key "AUTOLOADER" in
/home/marginalie/public_html/web/typo3conf/ext/autoloader/Classes/Utility/ExtendedUtility.php
line 80
```

**Comment by lochmueller** [comment]
Hey @lorisnico2000 
Already fixed in current master: https://github.com/lochmueller/autoloader/commit/674a1fd0ccd991c4bd95e844dea291e209a22170

Regards,
Tim
