### ISSUE TITLE
TYPO3_MODE should not be used in ext_tables.php and ext_localconf.php, use defined('TYPO3') or die();

### ISSUE THREAD

**Issue by sypets** [lochmueller/autoloader#199]
AFAIK, this will not break anything now but might in the future.

**Documentation**:

> You MUST NOT check for values of the removed TYPO3_MODE or TYPO3_REQUESTTYPE constants (e.g. if (TYPO3_MODE === 'BE')) or the ApplicationType within these files as it limits the functionality to cache the whole systems' configuration. Any extension author should remove the checks, and re-evaluate if these context-depending checks could go inside the hooks / caller function directly., e.g. do not do:

```
// do NOT do this:
-if (TYPO3_MODE === 'BE')

```

> You SHOULD check for the existence of the constant defined('TYPO3') or die(); at the top of ext_tables.php and ext_localconf.php files right after the use statements

```

<?php
// example for use statement, only add if using this class
use TYPO3\CMS\Core\Utility\ExtensionManagementUtility;
// put this at top of every ext_tables.php and ext_localconf.php right after
// the use statements
defined('TYPO3') or die();
```

https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/BestPractises/ConfigurationFiles.html#rules-and-best-practices

**Comment by lochmueller** [comment]
Hey @sypets ,
prepare this in current master (double check) and add notices in the code for an upcoming migration.
Regards,
Tim
