### ISSUE TITLE
Problems with FlexForms for ContentObjects

### ISSUE THREAD

**Issue by sirdiego** [lochmueller/autoloader#202]
Hi @lochmueller,

within the FlexForms loader there is a mechanism to load XML-Files from `Configuration/FlexForms/Content/` but this does not work anymore. My guess would be that this issue started with TYPO3 11 LTS.

The problem is with the way the autoloader registers the ContentObjects (inside the ContentObject loader via `ext_tables.php`) and the FlexForms (inside FlexForms loader via `TCA/Overrides/`).

A hotfix would be to move the `contentSignature` block from `TCA/Overrides/` to `ext_tables.php` inside the FlexForms loader. BUT it seems that would NOT be the right way to do it. I think that the whole ContentObjects loader needs some love. Calls to `ExtensionManagementUtility::addPlugin()` for example should not be called inside `ext_tables.php` (see DocBlock from core `FOR USE IN files in Configuration/TCA/Overrides/*.php Use in ext_tables.php FILES may break the frontend.` :joy:)

I'd love to talk to you about that.

**Comment by lochmueller** [comment]
Hey @sirdiego ,

do you check this: https://github.com/lochmueller/autoloader/commit/fcab32ca8ee4d08a3ff736a35a9d372c6dff83db and the last line of this note: https://github.com/lochmueller/autoloader/blob/master/Documentation/Loader/FlexForms.rst

Perhaps this is the problem and just a missing function call in the TCA overrides?

Regards,
Tim

**Comment by lochmueller** [comment]
I will close this issue... I think the patch and the documentation should fix this. Otherwise there is already a workaround.
