### ISSUE TITLE
typo3 12 support

### ISSUE THREAD

**Issue by amdeu** [lochmueller/autoloader#203]
Hi @lochmueller, 

any estimation on when typo3 v12 will be supported?

Thanks in advance

**Comment by lochmueller** [comment]
Hey @HomelessRaccoon ,
same as here: https://github.com/lochmueller/autoloader/issues/204 I will check this and there will be a new release, but there is no Agenda currently. Feel free to send PR.
Regards,
Tim

**Comment by KIDS-interactive** [comment]
Typo3 v12 is now already released for over half a year and nothing happend yet. We can't update our instances. What would be a fair sponsoring price?

**Comment by lochmueller** [comment]
Hey @KIDS-interactive ,

which functions do you need out of EXT:autoloader? There is no support out of the community (programming and/or financial) and public extensions are migrated from EXT:autoloader to modern core functions for TYPO3 v12 (like EXT:calendarize is already migrated). Please get in contact via Slack with me.

Regards,
Tim

**Comment by lochmueller** [comment]
I close this issue. No feedback anymore...

there are currently no plans for a v12 release. TYPO3 v12 and v13 using many PHP Attributes for "magic registration" and the SmartObject Feature could easly replaced with EXT:mask or content blocks in the feature.
