### ISSUE TITLE
php 8 attributes instead of annotations

### ISSUE THREAD

**Issue by amdeu** [lochmueller/autoloader#204]
Hi @lochmueller,

it would be nice if it was possible to use php 8 attributes as an alternative to the Autoloader Annotations, like 
```
#[DatabaseTable('tt_content')]
class Text extends ContentElement
...
```
Regards

**Comment by lochmueller** [comment]
Hey @HomelessRaccoon ,
that would be cool. It is on the Agenda for quite long, but there are no sponsors (perhaps code, money, ideas) so far. I will check this in my next OpenSource-Sprint...
Regards,
Tim

**Comment by lochmueller** [comment]
I will close this issue. See explanation here... https://github.com/lochmueller/autoloader/issues/203
