### ISSUE TITLE
Connect slot multiple times

### ISSUE THREAD

**Issue by mbrodala** [lochmueller/autoloader#22]
The documentation currently says the following about the `Slots` loader:

> ... So it is possible to connect one slot class with many signals.

However, [the code](https://github.com/lochmueller/autoloader/blob/60a1f1a206261f454c06d3d83dbd92234021f4a0/Classes/Loader/Slots.php#L52) leads to believe that only the first annotation pair is used, thus the following won't work:

```php
class MySlot {
  /**
   * @signalClass \Foo\Bar
   * @signalName mySignal
   * @signalClass \Foo\Qux
   * @signalName mySimilarSignal
   */
  public function doSomething() {}
}
```

Is this actually supported or could this be supported? In any case a code snippet in `Documentation/Loader/Slots` would be useful.

**Comment by lochmueller** [comment]
Thanks... I add a helper method to support multi line and also space separated configuration for Slots, Hooks and Aspects.
