### ISSUE TITLE
Modifying content elements with `addToAllTCAtypes` not possible

### ISSUE THREAD

**Issue by jousch** [lochmueller/autoloader#40]
I've tried to add a custom palette or an additional field with e.g. `\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addToAllTCAtypes('tt_content', 'assets', 'ccontent_homepage_slide', '');` without success.

When checking the TCA with the configuration backend module, no additional field is added.

**Comment by jousch** [comment]
Any updates on this issue?

**Comment by lochmueller** [comment]
Hey @jousch 
Do you call this in ext_tables.php or in the Overrides/tt_content.php? Does the change effect the first hit (after a clear cache)?
Regards,
Tim

**Comment by lochmueller** [comment]
No feedback. I close this issue. If the problem still exists please report a new issue...
