### ISSUE TITLE
Deleting class loading information in clear cache hook should be removed

### ISSUE THREAD

**Issue by helhum** [lochmueller/autoloader#46]
What is the purpose of these lines here?
https://github.com/lochmueller/autoloader/blob/master/Classes/Hooks/ClearCache.php#L65-L70

Removing these files can have weird side effects and should be avoided at all costs.

Instead the class loading information should be re-generated if required.
The API for that is pretty simple: https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/extensionmanager/Classes/Command/ExtensionCommandController.php#L95

**Comment by lochmueller** [comment]
Hey @helhum ,

this is right. Very simple API. Replaced in current master...

Thanks
