### ISSUE TITLE
API should be used to register Ajax command

### ISSUE THREAD

**Issue by helhum** [lochmueller/autoloader#47]
Instead of manipulating the configuration array here: https://github.com/lochmueller/autoloader/blob/master/ext_localconf.php#L28

The API method should be used
`\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::registerAjaxHandler`

This avoids potential CSRF issues with the Ajax calls

**Comment by lochmueller** [comment]
Changed to the register function... thanks
