### ISSUE TITLE
[BUGFIX] translations ares sometimes added twice

### ISSUE THREAD

**Issue by jousch** [lochmueller/autoloader#5]
Sometimes `PLUGINNAME` and `PLUGINNAME.DESCRIPTION` is added twice to xlf file when adding new content object.

**Comment by lochmueller** [comment]
It seems to be a problem of the core. After each added label the cache of the "l10n" is cleard via clearCache of the AbstractLocalizationWriter. Furthermore LanguageHandler use a static "$createdLabelCache" to check the labels in one request. So it is difficult to get this bug...

**Comment by lochmueller** [comment]
perhaps this issue is solved also in 1.9.0 because the LANG object is build, if there is no language service available... Alternatively I have no clue :(
