### ISSUE TITLE
Version 2.0.1 is released to TER seems faulty

### ISSUE THREAD

**Issue by helhum** [lochmueller/autoloader#50]
2.0.1 does not contain the latest fixes here in master, at least this one is missing: https://github.com/lochmueller/autoloader/commit/50b4a0df8d4f3cf818a79c653485fb22c46e52fe

Besides that, I am missing the tags for these versions in this repo

**Comment by lochmueller** [comment]
https://github.com/lochmueller/autoloader/releases/tag/2.0.2
TER version in a few minutes...
Regards,
Tim

**Comment by helhum** [comment]
thanks, for the amazingly fast response times! :+1:
