### ISSUE TITLE
adapt path for partials/templates

### ISSUE THREAD

**Issue by pniederlag** [lochmueller/autoloader#52]
is there an option/configuration to adapt the path(S) for partials and/or templates for Content Objects?

**Comment by lochmueller** [comment]
At the moment the Path to the template is build via extension key and object name as Standalone View:
https://github.com/lochmueller/autoloader/blob/master/Classes/Controller/ContentController.php#L54

I will check if there is a smarty integration for override (also set Partials-path)....

**Comment by bernhardberger** [comment]
I think there is..

I built something similar to your extension (on a much smaller scale) for custom content elements and I pretty much solved it like this:

`   protected function initializeView(\TYPO3\CMS\Extbase\Mvc\View\ViewInterface $view)
    {
        $configuration = $this->configurationManager->getConfiguration(\TYPO3\CMS\Extbase\Configuration\ConfigurationManagerInterface::CONFIGURATION_TYPE_FRAMEWORK);
        $viewConfiguration = $configuration['view'];

        if (isset($viewConfiguration['file'])) {
            $this->view = $this->objectManager->get('TYPO3\CMS\Fluid\View\StandaloneView');
            $this->view->setTemplatePathAndFilename(GeneralUtility::getFileAbsFileName($viewConfiguration['file']));
        }
        if (isset($viewConfiguration['layoutRootPaths'])) {
            $this->view->setLayoutRootPaths($viewConfiguration['layoutRootPaths']);
        }
        if (isset($viewConfiguration['partialRootPaths'])) {
            $this->view->setPartialRootPaths($viewConfiguration['partialRootPaths']);
        }
    }`

**Comment by lochmueller** [comment]
Added with https://github.com/lochmueller/autoloader/commit/bb8552a644a3f4c7776ae1e5dc00167de18d7638
Perhaps we should add same "special" logic to change the templates just for a few content elements... I will check this in the next days...
