### ISSUE TITLE
Installing autoloader via composer throws InvalidArgumentException

### ISSUE THREAD

**Issue by rebeccakuba** [lochmueller/autoloader#53]
Hello,
I tried to install autoloader via composer on V 7.6.1 and received the following exception:

[InvalidArgumentException]                                                                                    
Could not find package typo3-ter/autoloader at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability.

Could you give me a feedback, please. Thanks!

**Comment by lochmueller** [comment]
Hey @rebeccakuba 

The autoloader is part of the composer repository.
https://composer.typo3.org/satis.html#!/autoloader

Please try to enter a valid version?!

Regards,
Tim

**Comment by phogl** [comment]
Did you install TYPO3 Core through composer?

You may need to define the TYPO3 composer repository in your composer.json file:

```
"repositories": [
        {
            "type": "composer",
            "url": "https://composer.typo3.org/"
        }
],
```
If this has not been defined composer would only check for available packages at packagist.org, which is not used by TYPO3 ecosystem ..

Habve a look at the "How to use it" section at https://composer.typo3.org/

**Comment by rebeccakuba** [comment]
Thank you very much @lochmueller @phogl! I've forgotten to add repositories to composer.json. Now it's working :).

**Comment by lochmueller** [comment]
Great. Have fun with the EXT:autoloader...
