### ISSUE TITLE
Enable cache clearing in production context

### ISSUE THREAD

**Issue by jousch** [lochmueller/autoloader#54]
We often have troubles with the autoloader cache after deploying new features or after updating the TYPO3 core. The TCA modifications by autoloader aren't loaded and we have to manually clear the autoloader cache.

Is it possible - from your view - to only check if you are an TYPO3 backend admin. Or maybe something advanced like: If main context is production, and actual user is admin and has set an option to enable the clear cache button.

What do you think Tim? Actually I often has these scenarios. How do you prevent such stuff?

**Comment by phogl** [comment]
+1 for that. Indeed we wasn't aware that the availability of the button depends on the given Context. We're always wondering why that button does not appear on our production systems ...

I would agree that this button should always be available to admin users.

**Comment by lochmueller** [comment]
Hey @jousch ,
Hey @phogl ,

I think the patch is a good compromise ;) You can enable the menu for production via extension manager...

Regards,
Tim

**Comment by phogl** [comment]
Great work, thank you!
