### ISSUE TITLE
JSON-RPC Loader

### ISSUE THREAD

**Issue by fduarte42** [lochmueller/autoloader#60]
Hi, 
I'm trying to write a JSON-RPC Server Loader, but I have trouble integrating the Zend/Json/Server Library in your Project under the Contrib directory. I changed the composer.json in Contrib and the did a composer update and a composer dumpautoload -o to have a autoload_classmap.php. But know even the SoapServer is not working anymore. Should I do a Pull-Request? I forked the project under fduarte42/autoloader. Do you have any advice?

Kind regards,

Tito

**Comment by lochmueller** [comment]
Hey @fduarte42 
nice work. I fix the loading of the lib for the SoapServer in the current master:
https://github.com/lochmueller/autoloader/commit/e818d2f15fe5046867a292b78af0cc77c5c4a226

important steps are:
- After you load the package in Resource/Private/Contrib run "composer dumpautoload -o"
- Add a test that load the foreign classes: https://github.com/lochmueller/autoloader/blob/e818d2f15fe5046867a292b78af0cc77c5c4a226/Tests/Unit/Service/SoapServerTest.php
- Add the namespaces to the PSR-4 part of the base composer.json https://github.com/lochmueller/autoloader/blob/e818d2f15fe5046867a292b78af0cc77c5c4a226/composer.json

Please tak care of the botth last steps. If this will not fix your problem, please contact me again ;) You can also pull that request after you check that steps...

Regards,
Tim

**Comment by fduarte42** [comment]
I think we can close this issue now. Thanks for helping.
