### ISSUE TITLE
Unable to install version 2 on TYPO3 6.2

### ISSUE THREAD

**Issue by hirnschmalz** [lochmueller/autoloader#67]
I tried to install the extension in a TYPO3 6.2 installation. The extension could not be activated since it requires `typo3/cms` in the `composer.json` (BTW the same problem with the `faq`extension).

**Comment by lochmueller** [comment]
Hey @hirnschmalz 
Do you have a smart solution? Do you use the composer mode of the TYPO3 Core?
Just drop the line in the requirements?
Regards,
Tim

**Comment by hirnschmalz** [comment]
No, not really a smart solution since I don't user composer for the TYPO3 Core ;)
I already created a patchfile for my installation to make CI working.

Markus

**Comment by lochmueller** [comment]
I think we can drop the line in the requirements, because the Travis configuration execute "composer require typo3/cms=$TYPO3_VERSION" so travis should still work. Do you want to create a pull request?
