### ISSUE TITLE
Content Object: Wrong icon path in Content/Page overview [Typo3 7.6.15]

### ISSUE THREAD

**Issue by benwick** [lochmueller/autoloader#76]
Hi,

the icon of content objects is not displayed in the Content/Page overview. [Here is an image of the case.](http://fs5.directupload.net/images/170131/hhzbbmre.jpg) 

The icon is correctly named and placed - and shown, when I add the content element. In the overview of the content elements, there is added an extra subfolder to the icon link. Here is an example: My Typo3 installation is at `http://some.toplevel.domain/some-site/` 
The generated icon link then is  `/some-site/some-site/typo3conf/ext/some-extension/Resources/Public/Icons/Content/ContentElement.svg` 
That is wrong and one subfolder too much.

**Comment by benwick** [comment]
If the Typo3 installation is not in a subfolder, the icon will be shown.

**Comment by lochmueller** [comment]
Which TYPO3 version du you use? I think it is a 6.2 problem, right?

Regards,
Tim

**Comment by benwick** [comment]
The version is in the title :) It is Typo3 7.6.15.

**Comment by lochmueller** [comment]
Sorry... my mistake. I will check this in the next week...
