### ISSUE TITLE
Content Objects and FAL translations

### ISSUE THREAD

**Issue by Isaegenuet** [lochmueller/autoloader#77]
Hi Tim

Thank you for your work and this very useful extension!

I stumbled yesterday upon a problem with the translation of FAL records. I've created the content object with the following annotation:

`@var \TYPO3\CMS\Extbase\Domain\Model\FileReference`

The TCA part:

`'tx_xyz_image' => array(
            'config' => \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::getFileFieldTCAConfig('image', array(
                'appearance' => array(
                    'createNewRelationLinkTitle' => 'LLL:EXT:cms/locallang_ttc.xlf:images.addFileReference'
                ),
                'foreign_types' => array(
                    2 => array(
                        'showitem' => '--palette--;LLL:EXT:lang/locallang_tca.xlf:sys_file_reference.imageoverlayPalette;imageoverlayPalette, --palette--;;filePalette'
                    )
                ),
                'minitems' => 0,
                'maxitems' => 1,
            ),
                $GLOBALS['TYPO3_CONF_VARS']['GFX']['imagefile_ext']),
        ),`

Maybe i miss something, but i get always the image object from the record from default language.

Thank you.

Best,
René

**Comment by jousch** [comment]
This is a extbase bug :-(

Did you tried https://github.com/froemken/repair_translation

**Comment by lochmueller** [comment]
Oh... you are right: We ar using this one: https://bitbucket.org/t3easy_de/faltranslation

This is the related core bug: https://forge.typo3.org/issues/57272

**Comment by lochmueller** [comment]
I close this issue, because the both extension should fix the problem...
