### ISSUE TITLE
Start and end time of events become 4 hours less after saving

### ISSUE THREAD

**Issue by mediaessenz** [lochmueller/autoloader#79]
Under TYPO3 Version 8.7.0, start and end time of events become 4 hours less after saving.

If I e.g. enter 00:00 into field "start time", it becomes 20:00 after pressing save.
If I press the save button again, it become 18:00 (**2** hours less), next time 16:00 and so on. 

The problem also exists at the datetime field "start" under tab "access" of calendar records, 
but **neither** in records of other extensions e.g. news **nor** in content elements.

I thing the problem stock somewhere inside the IndexPreperationService method prepareRecordForDatabase.
If I e.g. enter 00:00 into start time field and press save, this value becomes 1491422400 inside $record['start_time'], which correspond to 05.04.2017 22:00:00 in local time and 05.04.2017 20:00:00 in utc. Apart of the date this ist exactly the value I see after page reloads.

I thing in general, the value of "start_time" and "end_time" should **not** be greater than 86400 (because time) at this place. But if I look in the database table "tx_calendarize_domain_model_index", all values are greater, beside some "end_date" values, which I leave empty.
If I look into the database of an other TYPO3 installation, but Version 7.6, all values are smaller than 86400.

**Comment by lochmueller** [comment]
I think this bug is related to EXT:calendarize https://github.com/lochmueller/calendarize not autoloader. I will check this...

**Comment by mediaessenz** [comment]
Of course, sorry, my fault. 
Should I add this issue there again?

**Comment by lochmueller** [comment]
That would be great. Then we can close this one here...
