### ISSUE TITLE
autoloader do not add renderType "inputDateTime" to TCA of starttime and endttime under TYPO3 8.7

### ISSUE THREAD

**Issue by mediaessenz** [lochmueller/autoloader#87]
If I press "Check TCA Migrations" in the installtool of TYPO3 8.7 I get notifications like this of a extension using autoloaders TCA loader:
```
The TCA setting 'renderType' => 'inputDateTime' was added in TCA tx_domaincheck_domain_model_tld['columns']['starttime']['config']
```

**Comment by lochmueller** [comment]
Already fixed in current master:
https://github.com/lochmueller/autoloader/commit/288a12042e007510d014514cac0e849ec0ec8a7b
