### ISSUE TITLE
autoloader add deprecated "max" parameter to TCA of starttime and endttime under TYPO3 8.7

### ISSUE THREAD

**Issue by mediaessenz** [lochmueller/autoloader#88]
If I press "Check TCA Migrations" in the installtool of TYPO3 8.7 I get notifications like this of a extension using autoloaders TCA loader:
```
The config option 'max' has been removed from the TCA for renderType='inputDateTime' in tx_domaincheck_domain_model_tld['columns']['starttime']['config']['max']
```

**Comment by lochmueller** [comment]
Already dropped in master. Please check the Git master before issues are created.

Regards,
Tim
