### ISSUE TITLE
[BUGFIX] BE page module viewhelper didn't work with TYPO3 6-2

### ISSUE THREAD

**Issue by jousch** [lochmueller/autoloader#9]
`<a:be.editLink />` didn't work in 6-2.

**Comment by lochmueller** [comment]
Hey @jousch 
Please try this patch.... https://github.com/lochmueller/autoloader/commit/99e15b0dd7cd082b2608139edee3b61cba828ed8

Does it work?

Regards,
Tim

**Comment by jousch** [comment]
Doesn't work with 6-2. I've tested it with the latest commit: 664500df6d48208fe5a7df69f69a18a2b2e8b3eb

**Comment by jousch** [comment]
Thanks, now it works!
